### ISSUE TITLE
Problems caused by strict allow-net

### ISSUE THREAD

**Issue by eunhyulkim** [chibat/heroku-buildpack-deno#12]
The lines 54–60 in the compile file show that the allowed hosts in the allow-net are strictly limited. For me, I use jsdelivr.net and mongodb-atlas additionally. The build failed. In my case, I modified the source code to allow that host. Is there an option but I don't know? Or is it something that needs to be modified?

```
if [ -f aleph.config.ts -a -f import_map.json ]
then
  ALEPH_PATH=$(jq -r '.imports."aleph/"' import_map.json)
  $BIN_DIR/deno run --allow-net=deno.land,cdn.jsdelivr.net,esm.sh,cdn.esm.sh --allow-read=$HOME,$BUILD_DIR/.heroku --allow-write --allow-env --allow-run ${ALEPH_PATH}cli.ts build
  $BIN_DIR/deno run --allow-net=deno.land ${ALEPH_PATH}cli.ts start --help > /dev/null
  cp -rp .aleph $BUILD_DIR/.
fi
```

**Comment by chibat** [comment]
The latest version does not limit hosts.
https://github.com/chibat/heroku-buildpack-deno/blob/4e49acc018841700af94b26caf92c92a81572fee/bin/compile#L67

I also recommend customizing the build.
https://github.com/chibat/heroku-buildpack-deno#customizing-the-build-process

[example project](https://github.com/chibat/heroku-deno-customized-build-example)

**Comment by eunhyulkim** [comment]
That’s great! Thank you!
