### ISSUE TITLE
Heroku Config Vars

### ISSUE THREAD

**Issue by tedrand** [chibat/heroku-buildpack-deno#2]
Does this build-pack support Config Vars set from the Heroku dashboard?

const key = Deno.env.toObject().SECRET_KEY;

**Comment by chibat** [comment]
I think that you can get Config Vars, if you add `--allow-env` flag to your `deno` command line in Procfile.

**Comment by tedrand** [comment]
Yep, thanks and sorry for not closing this earlier. I was having issues with the dotenv library that I hadn’t had with node but I think that has more to do with Deno not allowing for conditional imports.
