### ISSUE TITLE
Property 'openPlugin' does not exist on type 'typeof Deno' despite --unstable flag being present in Procfile

### ISSUE THREAD

**Issue by ghost** [chibat/heroku-buildpack-deno#3]
When deploying locally using the following command:

`deno run --allow-net --allow-write --allow-read --unstable --allow-plugin server.ts`

There are no errors. Works.  

When deploying to Heroku with the following inside of the Procfile:

`web: deno run --allow-net=:${PORT} --allow-write --allow-read --unstable --allow-plugin --cached-only server.ts --port=${PORT} at https://deno.land/x/plugin_prepare@v0.6.0/mod.ts:64:15
`
I get the following error: 

`error: TS2339 [ERROR]: Property 'openPlugin' does not exist on type 'typeof Deno'.
remote:   return Deno.openPlugin(localPath);`

**Comment by chibat** [comment]
I fixed this issue.
Thanks for your report !
